<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <RootNamespace>AutoSphere.VehicleGateway</RootNamespace>
    <UserSecretsId>autosphere-gateway</UserSecretsId>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AutoSphere.VehicleSignals/AutoSphere.VehicleSignals.csproj" />
    <ProjectReference Include="../AutoSphere.Diagnostics/AutoSphere.Diagnostics.csproj" />
    <ProjectReference Include="../../shared/AutoSphere.Contracts/AutoSphere.Contracts.csproj" />
    <ProjectReference Include="../../simulator/AutoSphere.EcuSimulation/AutoSphere.EcuSimulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

</Project>
