using ThermoTwin.Numerics.Analysis;
using ThermoTwin.Numerics.Grid;
using ThermoTwin.Numerics.Inverse;
using ThermoTwin.Numerics.LinearAlgebra;
using ThermoTwin.Numerics.Optimization;
using ThermoTwin.Numerics.Pde;
using ThermoTwin.Numerics.Physics;
using ThermoTwin.Numerics.Prediction;
using ThermoTwin.Numerics.Sensors;

namespace ThermoTwin.Tests.Numerics;

public sealed class InverseAndControlTests
{
    private static readonly Grid2D Grid = new(20, 10, 0.2, 0.1);

    private static ThermalModel Model() => new(Grid, MaterialProperties.LithiumIonPouchCell,
        BoundaryConditions.All(BoundaryCondition.Convective(25, 10)), new CoolingModel(22, 5, 120, 150));

    [Fact]
    public void Sensor_interpolation_is_exact_for_linear_fields()
    {
        var field = Grid.CreateField((x, y) => 3 + 20 * x - 7 * y);
        var network = new SensorNetwork(Grid, [new Sensor("A", 0.033, 0.041), new Sensor("B", 0.151, 0.077)]);
        var y = network.Observe(field);
        Assert.Equal(3 + 20 * 0.033 - 7 * 0.041, y[0], 10);
        Assert.Equal(3 + 20 * 0.151 - 7 * 0.077, y[1], 10);
    }

    [Fact]
    public void Gaussian_noise_has_requested_moments_and_is_reproducible()
    {
        var a = new GaussianNoise(0.2, 5);
        var samples = Enumerable.Range(0, 20000).Select(_ => a.Next()).ToArray();
        Assert.InRange(samples.Average(), -0.01, 0.01);
        Assert.InRange(Math.Sqrt(samples.Select(s => s * s).Average()), 0.19, 0.21);
        var b = new GaussianNoise(0.2, 5);
        Assert.Equal(samples[0], b.Next());
    }

    [Fact]
    public void Load_profile_interpolates_linearly_and_clamps()
    {
        var p = LoadProfile.FastChargeCcCv(1200, 1800, 0.25);
        Assert.Equal(0, p.At(0));
        Assert.Equal(0.5, p.At(15), 10);
        Assert.Equal(1, p.At(600));
        Assert.Equal(0.25, p.At(5000));
    }

    [Fact]
    public void Noise_free_data_from_the_model_recovers_the_source_coefficients()
    {
        // Inverse-crime setting on purpose: data generated by the estimator's own model with a source in the basis span.
        var solver = new HeatEquationSolver(Model(), TimeScheme.CrankNicolson, 5);
        var basis = new SourceBasis(Grid, 5, 3);
        var sensors = SensorNetwork.Layout(0.2, 0.1, 15);
        var network = new SensorNetwork(Grid, sensors);
        var load = LoadProfile.Constant();
        var truthCoefficients = Enumerable.Range(0, basis.Count).Select(j => 20 + 10 * Math.Sin(j)).ToArray(); // kW/m³
        var source = basis.Expand(truthCoefficients, InverseHeatSourceEstimator.CoefficientScale);
        var estimator = new InverseHeatSourceEstimator(solver, basis, network, load, Grid.CreateField(25));

        var t = Grid.CreateField(25);
        var next = new double[t.Length];
        for (var n = 0; n < 120; n++)
        {
            solver.Step(t, next, source, source, 0.3);
            (t, next) = (next, t);
            estimator.Assimilate(0.3, network.Observe(t));
        }

        var solution = estimator.Solve(1e-12, RegularizationKind.Identity);
        Assert.True(ErrorMetrics.RelativeL2(solution.Coefficients, truthCoefficients) < 1e-3);
        Assert.True(ErrorMetrics.Rmse(solution.TemperatureField, t) < 1e-6);
    }

    [Fact]
    public void Tikhonov_residual_grows_and_seminorm_shrinks_with_lambda()
    {
        var estimator = NoisyEstimator(out _, out _);
        var lambdas = Vector.LogSpace(1e-7, 1e1, 9);
        var solutions = lambdas.Select(l => estimator.Solve(l, RegularizationKind.Gradient)).ToArray();
        for (var i = 1; i < solutions.Length; i++)
        {
            Assert.True(solutions[i].ResidualNorm >= solutions[i - 1].ResidualNorm - 1e-9);
            Assert.True(solutions[i].SolutionSeminorm <= solutions[i - 1].SolutionSeminorm + 1e-9);
        }
    }

    [Fact]
    public void Gcv_selects_a_lambda_that_localises_the_hidden_hotspot()
    {
        var estimator = NoisyEstimator(out var hotspot, out _);
        var lambda = estimator.GcvLambda(RegularizationKind.Gradient);
        var solution = estimator.Solve(lambda, RegularizationKind.Gradient);
        var detected = HotspotDetector.Detect(Grid, solution.SourceField);

        Assert.NotNull(detected);
        var error = Math.Sqrt(Math.Pow(detected.X - hotspot.X, 2) + Math.Pow(detected.Y - hotspot.Y, 2));
        Assert.True(error < 0.02, $"localisation error {error * 1000:0.0} mm");

        var lcurve = estimator.ComputeLCurve(RegularizationKind.Gradient, points: 20);
        Assert.InRange(lcurve.CornerIndex, 1, lcurve.Points.Count - 2);
    }

    [Fact]
    public void Hotspot_detector_finds_gaussian_centre_and_ignores_flat_fields()
    {
        var spot = new GaussianHotspot(0.12, 0.04, 100, 0.01);
        var field = Grid.CreateField((x, y) => 10 + spot.Evaluate(x, y));
        var h = HotspotDetector.Detect(Grid, field)!;
        Assert.InRange(h.X, 0.11, 0.13);
        Assert.InRange(h.Y, 0.03, 0.05);
        Assert.Null(HotspotDetector.Detect(Grid, Grid.CreateField(10)));
    }

    [Fact]
    public void Cooling_optimiser_satisfies_constraint_with_less_energy_than_best_constant_level()
    {
        var model = Model();
        var load = LoadProfile.FastChargeCcCv(600, 900, 0.2);
        var predictor = new ThermalPredictor(new HeatEquationSolver(model, TimeScheme.CrankNicolson, 10), load);
        var optimizer = new CoolingOptimizer(predictor);
        var source = Grid.CreateField((x, y) => 55_000 + new GaussianHotspot(0.13, 0.06, 450_000, 0.015).Evaluate(x, y));
        var initial = Grid.CreateField(25);
        var options = new CoolingOptimizationOptions(SafeTemperature: 38, Segments: 9, SegmentDuration: 100, MaxIterationsPerStage: 25);

        var uncooled = optimizer.EvaluatePlan(initial, source, 0, CoolingPlan.Constant(0, 9, 100), options);
        Assert.True(uncooled.PeakTemperature > 38, "test requires an active constraint");

        var result = optimizer.Optimize(initial, source, 0, options);
        var constant = optimizer.MinimumFeasibleConstantLevel(initial, source, 0, options);
        var constantPlan = optimizer.EvaluatePlan(initial, source, 0, CoolingPlan.Constant(constant, 9, 100), options);

        Assert.True(result.Feasible, $"peak {result.PeakTemperature}");
        Assert.All(result.Plan.Levels, u => Assert.InRange(u, 0, 1));
        Assert.True(result.CoolingEnergy <= constantPlan.Forecast.CoolingEnergy * 1.001,
            $"optimised {result.CoolingEnergy:0} J vs constant {constantPlan.Forecast.CoolingEnergy:0} J");
        Assert.NotEmpty(result.History);
    }

    private static InverseHeatSourceEstimator NoisyEstimator(out GaussianHotspot hotspot, out double[] truth)
    {
        // Plant on a 2× finer grid (no inverse crime), noisy sensors, estimator on the coarse grid.
        var fine = new Grid2D(40, 20, 0.2, 0.1);
        var model = Model();
        var plantSolver = new HeatEquationSolver(model.WithGrid(fine), TimeScheme.CrankNicolson, 10);
        hotspot = new GaussianHotspot(0.135, 0.062, 450_000, 0.014);
        var spot = hotspot;
        var source = fine.CreateField((x, y) => 55_000 + spot.Evaluate(x, y));
        var sensors = SensorNetwork.Layout(0.2, 0.1, 12);
        var plantSensors = new SensorNetwork(fine, sensors);
        var noise = new GaussianNoise(0.1, 1);
        var estimator = new InverseHeatSourceEstimator(new HeatEquationSolver(model, TimeScheme.CrankNicolson, 10),
            new SourceBasis(Grid, 11, 6), new SensorNetwork(Grid, sensors), LoadProfile.Constant(), Grid.CreateField(25));

        var t = fine.CreateField(25);
        var next = new double[t.Length];
        for (var n = 0; n < 90; n++)
        {
            plantSolver.Step(t, next, source, source, 0.15);
            (t, next) = (next, t);
            estimator.Assimilate(0.15, plantSensors.Measure(t, noise));
        }

        truth = Grid.RestrictFrom(fine, source);
        return estimator;
    }
}
