// <auto-generated />
using System;
using AnomalyDetection.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnomalyDetection.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnomalyDetectionDbContext))]
    [Migration("20261001121040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.AnomalyRecord", b =>
                {
                    b.Property<Guid>("AnomalyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("anomaly_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("environment");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anomaly");

                    b.Property<DateTime?>("LastReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at_utc");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version");

                    b.Property<string>("ReasonSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason_summary");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Unreviewed")
                        .HasColumnName("review_state");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<Guid>("ScoringRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_record_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_name");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end_utc");

                    b.Property<Guid>("WindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("window_id");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_utc");

                    b.HasKey("AnomalyId")
                        .HasName("pk_anomaly_record");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_anomaly_record_created_at_utc");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_anomaly_record_model_id");

                    b.HasIndex("Score")
                        .HasDatabaseName("ix_anomaly_record_score");

                    b.HasIndex("ScoringRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_anomaly_record_scoring_record_id");

                    b.HasIndex("ReviewState", "CreatedAtUtc")
                        .HasDatabaseName("ix_anomaly_record_review_state_created_at_utc");

                    b.HasIndex("WindowId", "ModelId")
                        .IsUnique()
                        .HasDatabaseName("ix_anomaly_record_window_id_model_id");

                    b.HasIndex("ServiceName", "Environment", "WindowStartUtc")
                        .HasDatabaseName("ix_anomaly_record_service_name_environment_window_start_utc");

                    b.ToTable("anomaly_record", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.AnomalyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnomalyId")
                        .HasColumnType("uuid")
                        .HasColumnName("anomaly_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("previous_state");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reviewer");

                    b.HasKey("Id")
                        .HasName("pk_anomaly_review");

                    b.HasIndex("AnomalyId", "CreatedAtUtc")
                        .HasDatabaseName("ix_anomaly_review_anomaly_id_created_at_utc");

                    b.ToTable("anomaly_review", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("result");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_event_occurred_at_utc");

                    b.HasIndex("Action", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_event_action_occurred_at_utc");

                    b.ToTable("audit_event", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.FeatureWindow", b =>
                {
                    b.Property<Guid>("WindowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("window_id");

                    b.Property<double>("AuthFailureRate")
                        .HasColumnType("double precision")
                        .HasColumnName("auth_failure_rate");

                    b.Property<double>("AvgDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_duration_ms");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DependencyFailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("dependency_failure_count");

                    b.Property<double>("EndpointEntropy")
                        .HasColumnType("double precision")
                        .HasColumnName("endpoint_entropy");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("environment");

                    b.Property<double>("ErrorRate")
                        .HasColumnType("double precision")
                        .HasColumnName("error_rate");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<string>("FeatureSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("feature_schema_version");

                    b.Property<DateTime?>("LastScoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scored_at_utc");

                    b.Property<string>("LastScoringError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_scoring_error");

                    b.Property<int>("LateEventCount")
                        .HasColumnType("integer")
                        .HasColumnName("late_event_count");

                    b.Property<DateTime?>("NextScoringAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_scoring_attempt_utc");

                    b.Property<double>("P95DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("p95duration_ms");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer")
                        .HasColumnName("request_count");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("ScoringAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_attempts");

                    b.Property<string>("ScoringStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scoring_status");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_definition_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_name");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end_utc");

                    b.Property<int>("WindowSizeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("window_size_minutes");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_utc");

                    b.HasKey("WindowId")
                        .HasName("pk_feature_window");

                    b.HasIndex("WindowStartUtc")
                        .HasDatabaseName("ix_feature_window_window_start_utc");

                    b.HasIndex("ScoringStatus", "NextScoringAttemptUtc")
                        .HasDatabaseName("ix_feature_window_scoring_status_next_scoring_attempt_utc");

                    b.HasIndex("ServiceName", "Environment", "WindowStartUtc")
                        .HasDatabaseName("ix_feature_window_service_name_environment_window_start_utc");

                    b.HasIndex("ServiceDefinitionId", "WindowStartUtc", "WindowEndUtc", "FeatureSchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_feature_window_service_definition_id_window_start_utc_windo");

                    b.ToTable("feature_window", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.ModelVersion", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<string>("ActivatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("activated_by");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("algorithm");

                    b.Property<string>("ArtifactPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("artifact_path");

                    b.Property<string>("ArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("artifact_sha256");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<string>("DeactivatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deactivated_by");

                    b.Property<string>("FeatureSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("feature_schema_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LibraryVersionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("library_versions_json");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<bool>("ProductionEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("production_eligible");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("integer")
                        .HasColumnName("random_seed");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("registered_by");

                    b.Property<string>("ThresholdObjective")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("threshold_objective");

                    b.Property<DateTime>("TrainedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trained_at_utc");

                    b.Property<DateTime?>("TrainingPeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("training_period_end_utc");

                    b.Property<DateTime?>("TrainingPeriodStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("training_period_start_utc");

                    b.Property<string>("ValidationMetricsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_metrics_json");

                    b.Property<double>("ValidationThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("validation_threshold");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version");

                    b.HasKey("ModelId")
                        .HasName("pk_model_version");

                    b.HasIndex("FeatureSchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_model_version_one_active_per_schema")
                        .HasFilter("is_active");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ix_model_version_model_version");

                    b.ToTable("model_version", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.OperationalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes_json");

                    b.Property<string>("AuthenticationResult")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("authentication_result");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DependencyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dependency_name");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_ms");

                    b.Property<string>("EndpointGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint_group");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("environment");

                    b.Property<bool>("ErrorFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("error_flag");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("EventTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("FeatureWindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_window_id");

                    b.Property<DateTime?>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at_utc");

                    b.Property<bool>("IsLate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_late");

                    b.Property<string>("ProcessingState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("processing_state");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_definition_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_name");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_operational_event");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_operational_event_correlation_id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_operational_event_event_id");

                    b.HasIndex("FeatureWindowId")
                        .HasDatabaseName("ix_operational_event_feature_window_id");

                    b.HasIndex("ReceivedAtUtc")
                        .HasDatabaseName("ix_operational_event_unindexed")
                        .HasFilter("indexed_at_utc IS NULL");

                    b.HasIndex("ProcessingState", "EventTimestampUtc")
                        .HasDatabaseName("ix_operational_event_processing_state_event_timestamp_utc");

                    b.HasIndex("ServiceDefinitionId", "EventTimestampUtc")
                        .HasDatabaseName("ix_operational_event_service_definition_id_event_timestamp_utc");

                    b.HasIndex("ServiceName", "Environment", "EventTimestampUtc")
                        .HasDatabaseName("ix_operational_event_service_name_environment_event_timestamp_");

                    b.ToTable("operational_event", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.QuarantinedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_id");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_codes");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SanitizedPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sanitized_payload_json");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_quarantined_event");

                    b.HasIndex("ReceivedAtUtc")
                        .HasDatabaseName("ix_quarantined_event_received_at_utc");

                    b.ToTable("quarantined_event", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.ScoringRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FeatureSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("feature_schema_version");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anomaly");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version");

                    b.Property<string>("ReasonSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason_summary");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons_json");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<DateTime>("ScoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at_utc");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<Guid>("WindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("window_id");

                    b.HasKey("Id")
                        .HasName("pk_scoring_record");

                    b.HasIndex("ModelId", "ScoredAtUtc")
                        .HasDatabaseName("ix_scoring_record_model_id_scored_at_utc");

                    b.HasIndex("WindowId", "ModelId")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_record_window_id_model_id");

                    b.ToTable("scoring_record", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.ServiceDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("environment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_service_definition");

                    b.HasIndex("Name", "Environment")
                        .IsUnique()
                        .HasDatabaseName("ix_service_definition_name_environment");

                    b.ToTable("service_definition", (string)null);
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.AnomalyRecord", b =>
                {
                    b.HasOne("AnomalyDetection.Domain.Entities.ModelVersion", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_record_model_version_model_id");

                    b.HasOne("AnomalyDetection.Domain.Entities.ScoringRecord", null)
                        .WithOne()
                        .HasForeignKey("AnomalyDetection.Domain.Entities.AnomalyRecord", "ScoringRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_record_scoring_records_scoring_record_id");

                    b.HasOne("AnomalyDetection.Domain.Entities.FeatureWindow", "Window")
                        .WithMany()
                        .HasForeignKey("WindowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_record_feature_window_window_id");

                    b.Navigation("Model");

                    b.Navigation("Window");
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.AnomalyReview", b =>
                {
                    b.HasOne("AnomalyDetection.Domain.Entities.AnomalyRecord", null)
                        .WithMany("Reviews")
                        .HasForeignKey("AnomalyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_anomaly_review_anomaly_record_anomaly_id");
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.FeatureWindow", b =>
                {
                    b.HasOne("AnomalyDetection.Domain.Entities.ServiceDefinition", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feature_window_services_service_definition_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.OperationalEvent", b =>
                {
                    b.HasOne("AnomalyDetection.Domain.Entities.FeatureWindow", null)
                        .WithMany()
                        .HasForeignKey("FeatureWindowId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operational_event_feature_window_feature_window_id");

                    b.HasOne("AnomalyDetection.Domain.Entities.ServiceDefinition", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operational_event_services_service_definition_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.ScoringRecord", b =>
                {
                    b.HasOne("AnomalyDetection.Domain.Entities.ModelVersion", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_record_model_version_model_id");

                    b.HasOne("AnomalyDetection.Domain.Entities.FeatureWindow", "Window")
                        .WithMany()
                        .HasForeignKey("WindowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_record_feature_window_window_id");

                    b.Navigation("Model");

                    b.Navigation("Window");
                });

            modelBuilder.Entity("AnomalyDetection.Domain.Entities.AnomalyRecord", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
