<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/backend/AutoSphere.Api/AutoSphere.Api.csproj" />
    <ProjectReference Include="../../src/gateway/AutoSphere.VehicleGateway/AutoSphere.VehicleGateway.csproj" />
    <ProjectReference Include="../../src/simulator/AutoSphere.VehicleSimulator/AutoSphere.VehicleSimulator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
