// <auto-generated />
using System;
using AutoSphere.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoSphere.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutoSphereDbContext))]
    partial class AutoSphereDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoSphere.Domain.Alerts.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("AlertKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alert_key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("ClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at");

                    b.Property<string>("EcuId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ecu_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("SignalPath")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("signal_path");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<double?>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<Guid>("VehicleKey")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_key");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("VehicleKey", "RaisedAt")
                        .HasDatabaseName("ix_alerts_vehicle_key_raised_at");

                    b.HasIndex("VehicleKey", "AlertKey", "ClearedAt")
                        .HasDatabaseName("ix_alerts_vehicle_key_alert_key_cleared_at");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Diagnostics.DiagnosticSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("diagnosis");

                    b.Property<string>("EcuId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ecu_id");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("requested_by");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<double?>("RoundTripMs")
                        .HasColumnType("double precision")
                        .HasColumnName("round_trip_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<double?>("VehicleDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("vehicle_duration_ms");

                    b.Property<Guid>("VehicleKey")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_key");

                    b.HasKey("Id")
                        .HasName("pk_diagnostic_sessions");

                    b.HasIndex("VehicleKey", "RequestedAt")
                        .HasDatabaseName("ix_diagnostic_sessions_vehicle_key_requested_at");

                    b.ToTable("diagnostic_sessions", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Diagnostics.DiagnosticTroubleCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("EcuId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ecu_id");

                    b.Property<string>("FaultCategory")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("fault_category");

                    b.Property<DateTimeOffset>("LastReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reported_at");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<byte>("StatusMask")
                        .HasColumnType("smallint")
                        .HasColumnName("status_mask");

                    b.Property<Guid>("VehicleKey")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_key");

                    b.HasKey("Id")
                        .HasName("pk_diagnostic_trouble_codes");

                    b.HasIndex("VehicleKey", "Status")
                        .HasDatabaseName("ix_diagnostic_trouble_codes_vehicle_key_status");

                    b.HasIndex("VehicleKey", "EcuId", "Code")
                        .HasDatabaseName("ix_diagnostic_trouble_codes_vehicle_key_ecu_id_code");

                    b.ToTable("diagnostic_trouble_codes", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.OtaCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.HasKey("Id")
                        .HasName("pk_ota_campaigns");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_ota_campaigns_package_id");

                    b.ToTable("ota_campaigns", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.OtaDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EcuId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ecu_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FromVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_version");

                    b.Property<string>("InstalledVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("installed_version");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_message");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<bool>("SimulateTransportCorruption")
                        .HasColumnType("boolean")
                        .HasColumnName("simulate_transport_corruption");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("ToVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_version");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid>("VehicleKey")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_key");

                    b.HasKey("Id")
                        .HasName("pk_ota_deployments");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_ota_deployments_campaign_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_ota_deployments_package_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ota_deployments_status");

                    b.HasIndex("VehicleKey", "CreatedAt")
                        .HasDatabaseName("ix_ota_deployments_vehicle_key_created_at");

                    b.ToTable("ota_deployments", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.OtaDeploymentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_ota_deployment_events");

                    b.HasIndex("DeploymentId", "Timestamp")
                        .HasDatabaseName("ix_ota_deployment_events_deployment_id_timestamp");

                    b.ToTable("ota_deployment_events", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.SoftwarePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("FirmwareDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("firmware_description");

                    b.Property<string>("MinimumCompatibleVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("minimum_compatible_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("payload_sha256")
                        .IsFixedLength();

                    b.Property<long>("PayloadSize")
                        .HasColumnType("bigint")
                        .HasColumnName("payload_size");

                    b.Property<string>("ReleaseNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("release_notes");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("signature");

                    b.Property<string>("SigningKeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signing_key_id");

                    b.Property<string>("TargetEcuType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_ecu_type");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_software_packages");

                    b.HasIndex("TargetEcuType", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_software_packages_target_ecu_type_version");

                    b.ToTable("software_packages", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Simulation.FaultInjectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Fault")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fault");

                    b.Property<string>("HandledBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("handled_by");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("result");

                    b.Property<string>("TargetEcuId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_ecu_id");

                    b.Property<Guid>("VehicleKey")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_key");

                    b.HasKey("Id")
                        .HasName("pk_fault_injections");

                    b.HasIndex("VehicleKey", "RequestedAt")
                        .HasDatabaseName("ix_fault_injections_vehicle_key_requested_at");

                    b.ToTable("fault_injections", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Telemetry.TelemetryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("SignalPath")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("signal_path");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<Guid>("VehicleKey")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_key");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_records");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_telemetry_records_timestamp");

                    b.HasIndex("VehicleKey", "SignalPath", "Timestamp")
                        .HasDatabaseName("ix_telemetry_records_vehicle_key_signal_path_timestamp");

                    b.ToTable("telemetry_records", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Vehicles.Ecu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveDtcCount")
                        .HasColumnType("integer")
                        .HasColumnName("active_dtc_count");

                    b.Property<long>("E2EErrorCount")
                        .HasColumnType("bigint")
                        .HasColumnName("e2e_error_count");

                    b.Property<string>("EcuId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ecu_id");

                    b.Property<string>("HardwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hardware_version");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("software_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("TimeoutCount")
                        .HasColumnType("bigint")
                        .HasColumnName("timeout_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleKey")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_key");

                    b.HasKey("Id")
                        .HasName("pk_ecus");

                    b.HasIndex("VehicleKey", "EcuId")
                        .IsUnique()
                        .HasDatabaseName("ix_ecus_vehicle_key_ecu_id");

                    b.ToTable("ecus", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Connectivity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("connectivity");

                    b.Property<DateTimeOffset?>("ConnectivityChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connectivity_changed_at");

                    b.Property<string>("GatewayId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gateway_id");

                    b.Property<string>("GatewaySoftwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gateway_software_version");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("health");

                    b.Property<DateTimeOffset?>("HealthEvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("health_evaluated_at");

                    b.Property<int>("HealthScore")
                        .HasColumnType("integer")
                        .HasColumnName("health_score");

                    b.Property<string>("HealthSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("health_summary");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<int>("ModelYear")
                        .HasColumnType("integer")
                        .HasColumnName("model_year");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<bool>("SimulationMode")
                        .HasColumnType("boolean")
                        .HasColumnName("simulation_mode");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_vehicle_id");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_vin");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Vehicles.VehicleHealthSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("VehicleKey")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_key");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_health_snapshots");

                    b.HasIndex("VehicleKey", "Timestamp")
                        .HasDatabaseName("ix_vehicle_health_snapshots_vehicle_key_timestamp");

                    b.ToTable("vehicle_health_snapshots", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoSphere.Domain.Alerts.Alert", b =>
                {
                    b.HasOne("AutoSphere.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_vehicles_vehicle_key");
                });

            modelBuilder.Entity("AutoSphere.Domain.Diagnostics.DiagnosticSession", b =>
                {
                    b.HasOne("AutoSphere.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diagnostic_sessions_vehicles_vehicle_key");
                });

            modelBuilder.Entity("AutoSphere.Domain.Diagnostics.DiagnosticTroubleCode", b =>
                {
                    b.HasOne("AutoSphere.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diagnostic_trouble_codes_vehicles_vehicle_key");
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.OtaCampaign", b =>
                {
                    b.HasOne("AutoSphere.Domain.Ota.SoftwarePackage", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ota_campaigns_software_packages_package_id");
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.OtaDeployment", b =>
                {
                    b.HasOne("AutoSphere.Domain.Ota.OtaCampaign", null)
                        .WithMany("Deployments")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ota_deployments_ota_campaigns_campaign_id");

                    b.HasOne("AutoSphere.Domain.Ota.SoftwarePackage", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ota_deployments_software_packages_package_id");

                    b.HasOne("AutoSphere.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ota_deployments_vehicles_vehicle_key");
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.OtaDeploymentEvent", b =>
                {
                    b.HasOne("AutoSphere.Domain.Ota.OtaDeployment", null)
                        .WithMany("Events")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ota_deployment_events_ota_deployments_deployment_id");
                });

            modelBuilder.Entity("AutoSphere.Domain.Simulation.FaultInjectionRecord", b =>
                {
                    b.HasOne("AutoSphere.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fault_injections_vehicles_vehicle_key");
                });

            modelBuilder.Entity("AutoSphere.Domain.Telemetry.TelemetryRecord", b =>
                {
                    b.HasOne("AutoSphere.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemetry_records_vehicles_vehicle_key");
                });

            modelBuilder.Entity("AutoSphere.Domain.Vehicles.Ecu", b =>
                {
                    b.HasOne("AutoSphere.Domain.Vehicles.Vehicle", null)
                        .WithMany("Ecus")
                        .HasForeignKey("VehicleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ecus_vehicles_vehicle_key");
                });

            modelBuilder.Entity("AutoSphere.Domain.Vehicles.VehicleHealthSnapshot", b =>
                {
                    b.HasOne("AutoSphere.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_health_snapshots_vehicles_vehicle_key");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoSphere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoSphere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("AutoSphere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoSphere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.OtaCampaign", b =>
                {
                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("AutoSphere.Domain.Ota.OtaDeployment", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("AutoSphere.Domain.Vehicles.Vehicle", b =>
                {
                    b.Navigation("Ecus");
                });
#pragma warning restore 612, 618
        }
    }
}
